<?php
namespace rpc_order;

/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

interface IOrderIf
{
    /**
     * @param \rpc_order\Order $order
     * @return \rpc_order\ReturnInfo
     */
    public function enOrder(\rpc_order\Order $order);
    /**
     * @param string $user
     * @param int $id
     * @param string $symbol
     * @return \rpc_order\ReturnInfo
     */
    public function cancelOrder($user, $id, $symbol);
    /**
     * @param string $symbol
     * @param int $durations
     * @return \rpc_order\ReturnInfo
     */
    public function cancelRobotOverTimeOrder($symbol, $durations);
    /**
     * @param string $user
     * @param int $id
     * @param string $symbol
     * @return \rpc_order\ReturnInfo
     */
    public function getOrder($user, $id, $symbol);
}
