<?php
namespace rpc_order;

/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;

final class OrderStatus
{
    const ORDER_SUBMIT = 1;

    const ORDER_FILLED = 2;

    const ORDER_PARTIAL_FILLED = 3;

    const ORDER_PARTIAL_CANCEL = 4;

    const ORDER_CANCELED = 5;

    const ORDER_CANCELING = 6;

    const ORDER_STATUSUNKNOW = 7;

    static public $__names = array(
        1 => 'ORDER_SUBMIT',
        2 => 'ORDER_FILLED',
        3 => 'ORDER_PARTIAL_FILLED',
        4 => 'ORDER_PARTIAL_CANCEL',
        5 => 'ORDER_CANCELED',
        6 => 'ORDER_CANCELING',
        7 => 'ORDER_STATUSUNKNOW',
    );
}

